spring.application.name=eureka-server
server.port=${EUREKA_PORT:8761}

# No se registra a sí mismo ni busca otros servidores Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Desactiva la auto-preservación en desarrollo para limpiar instancias caídas rápido
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
