name: Trigger auto deployment for freshsense-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/freshsense-backend-AutoDeployTrigger-daf24707-7a92-44f6-b224-297c1a4d7325.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FRESHSENSEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRESHSENSEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRESHSENSEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          registryUrl: freshsenseacr.azurecr.io
          registryUsername: ${{ secrets.FRESHSENSEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRESHSENSEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: freshsense-backend
          resourceGroup: freshsense-rg
          imageToBuild: freshsenseacr.azurecr.io/freshsense-backend:${{ github.sha }}


